apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fleet-sample-app
  name: fleet-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-sample-app
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: fleet-sample-app
        image: gmehta3/fleet-sample-app:v1
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-sample-app
  labels:
    app.kubernetes.io/name: fleet-sample-app
spec:
  selector:
    app.kubernetes.io/name: fleet-sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: fleet-sample-app
spec:
    rules:
    - host: hpa.demo
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            serviceName: fleet-sample-app
            servicePort: 8080